backend:
  name: git-gateway
  branch: master
locale: ja
media_folder: public/img
public_folder: img
collections:
- name: "blog"
  label: "Blog"
  folder: "content/blog"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "タイトル", name: "title", widget: "string"}
    - { label: "スラグ", name: "slug", widget: "string" }
    - { label: "公開日付", name: "date", widget: "datetime" }
    - { label: "本文", name: "body", widget: "markdown"}
